# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2a4b5e4741727aae33446635c0fd3d13402c9a81b0485dba2a94a5a77ec28116bdcca0a73d6d72ba869f4bdd9198c7588741eb00b9dafd09587932d8be48077

test:
  secret_key_base: f35927d5ec574b6de5cc81b3996625c3bd2ea5e0e5c9d7041cf017cf398b76ffbcbf6bab644e3120101fe987cce93f34f27433548b1eaa14a5b9a75066220adc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
